spring:
  application:
    name: test_agent
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-s4q7d35k5uyh6r3n.eu.auth0.com/

auth0:
  audience: https://users-api

server:
  port: ${PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
