apiVersion: v1
kind: Secret
metadata:
  name: node-frontend-secret
  namespace: __NAMESPACE__
stringData:
  AUTH0_CLIENT_ID: __AUTH0_CLIENT_ID__
  AUTH0_CLIENT_SECRET: __AUTH0_CLIENT_SECRET__
  SESSION_SECRET: __SESSION_SECRET__
