apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: __NAMESPACE__
type: Opaque
stringData:
  POSTGRES_DB: usersdb
  POSTGRES_USER: usersapp
  POSTGRES_PASSWORD: __POSTGRES_PASSWORD__
