apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: __NAMESPACE__
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16-alpine
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: postgres-secret
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 256Mi
        readinessProbe:
          exec:
            command: ["pg_isready", "-U", "usersapp", "-d", "usersdb"]
          initialDelaySeconds: 10
          periodSeconds: 5
